### ISSUE TITLE
RPLSplit returns an error when called without channels specified.

### ISSUE THREAD

**Issue by shihchengyen** [shihchengyen/PyHippocampus#17]
pyh.RPLSplit(saveLevel=1, SkipLFP=1, SkipHighPass=1, SkipSort=1, channel=[9, 31, 34, 56, 72, 93, 119, 120]) works, but when no channels are specified, this is what I see:
pyh.RPLSplit(saveLevel=1, SkipLFP=1, SkipHighPass=1, SkipSort=1)
Calling RPLParallel...
Object loaded from file rplparallel_72a7.hkl
Object created
/Volumes/User/shihcheng/anaconda3/lib/python3.7/site-packages/neo/io/proxyobjects.py:226: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  channel_indexes=self._global_channel_indexes[channel_indexes])
Traceback (most recent call last):

  File "<ipython-input-55-c30713078102>", line 1, in <module>
    pyh.RPLSplit(saveLevel=1, SkipLFP=1, SkipHighPass=1, SkipSort=1)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/PyHippocampus/PyHippocampus/rplsplit.py", line 27, in __init__
    DPT.DPObject.__init__(self, *args, **kwargs)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/DataProcessingTools/DataProcessingTools/objects.py", line 60, in __init__
    self.create(*args, **kwargs)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/PyHippocampus/PyHippocampus/rplsplit.py", line 123, in create
    data = segment.analogsignals[2].load(time_slice=None, channel_indexes=[chxIdx])

  File "/Volumes/User/shihcheng/anaconda3/lib/python3.7/site-packages/neo/io/proxyobjects.py", line 226, in load
    channel_indexes=self._global_channel_indexes[channel_indexes])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by anujsp2797** [comment]
Fixed this issue in the last commit.
