### ISSUE TITLE
aligning_objects: eyelink plot returning error after being modified.

### ISSUE THREAD

**Issue by shihchengyen** [shihchengyen/PyHippocampus#22]
PanGUI.create_window(el2)
Traceback (most recent call last):

  File "<ipython-input-124-3405dcf09926>", line 1, in <module>
    PanGUI.create_window(el2)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/PanGUI/PanGUI/main.py", line 372, in create_window
    window = window_class(plotobj, **kwargs)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/PanGUI/PanGUI/main.py", line 67, in __init__
    plotobj.plot(self.index, ax=ax, **self.plotopts[i])

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/PyHippocampus/PyHippocampus/eyelink.py", line 725, in plot
    trial_end_time = obj_timestamps[x[i][2].astype(int)] - 0.001

IndexError: index 12424000 is out of bounds for axis 0 with size 5546618

**Comment by akihumii** [comment]
should be solved by #31
